#!/bin/sh
# Managed by Salt

#[ -r /etc/lsb-release ] && . /etc/lsb-release
#
#if [ -z "$DISTRIB_RELEASE" ] && [ -x /usr/bin/lsb_release ]; then
#       # Fall back to using the very slow lsb_release utility
#       DISTRIB_RELEASE=$(lsb_release -sr)
#fi
#
#URL="https://help.ubuntu.com/"
#if uname -r | grep -qs "\-server"; then
#       URL="https://help.ubuntu.com/$DISTRIB_RELEASE/serverguide/C"
#fi
#
#printf "\n * Documentation:  %s\n" "$URL"

printf "\n * Private Property."
printf "\n * Unauthorized access is prohibited.\n"
